---
# GitHub Actions workflow for commits pushed to the SortCheckstyle repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java17-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew build javadoc runGoogle runPuppy runSelf runSun --console=plain --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: linux build
          path: app/build/distributions/app.tar

  Java25-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 25
      - run: ./gradlew build javadoc runGoogle runPuppy runSelf runSun --console=plain --stacktrace
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: windows build
          path: app/build/distributions/app.zip
