---
# GitHub Actions workflow for commits pushed to the SortCheckstyle repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/wrapper-validation@v5
      - run: ./gradlew -x checkstyleMain build javadoc runGoogle runPuppy runSelf runSun --console=plain --stacktrace

  Java21-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/wrapper-validation@v5
      - run: ./gradlew build javadoc runGoogle runPuppy runSelf runSun --console=plain --stacktrace
      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: app/build/distributions/app.tar

  Java26-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 26
      - run: ./gradlew build javadoc runGoogle runPuppy runSelf runSun --console=plain --stacktrace
        shell: bash
      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: app/build/distributions/app.zip
